// Generated by hibernate/SpringHibernateDaoImpl.vsl in andromda-spring-cartridge on $springUtils.date.
// license-header java merge-point
/**
 * This is only generated once! It will never be overwritten.
 * You can (and have to!) safely modify it by hand.
 */
package bw.co.roguesystems.comm.settings;

import bw.co.roguesystems.comm.email.EmailMessageRepository;
import jakarta.persistence.EntityNotFoundException;

import org.springframework.stereotype.Repository;

/**
 * @see Settings
 */
@Repository("settingsDao")
public class SettingsDaoImpl
    extends SettingsDaoBase
{
    
    public SettingsDaoImpl(
        EmailMessageRepository emailMessageRepository,
        SettingsRepository settingsRepository
    ) {

        super(
            emailMessageRepository,
            settingsRepository
        );
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void toSettingsDTO(
        Settings source,
        SettingsDTO target)
    {
        // TODO verify behavior of toSettingsDTO
        super.toSettingsDTO(source, target);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SettingsDTO toSettingsDTO(final Settings entity)
    {
        // TODO verify behavior of toSettingsDTO
        return super.toSettingsDTO(entity);
    }

    /**
     * Retrieves the entity object that is associated with the specified value object
     * from the object store. If no such entity object exists in the object store,
     * a new, blank entity is created
     */
    private Settings loadSettingsFromSettingsDTO(SettingsDTO settingsDTO)
    {
        if (settingsDTO.getId() == null)
        {
            return  Settings.Factory.newInstance();
        }
        else
        {
            return this.settingsRepository.findById(settingsDTO.getId())
                .orElseThrow(() -> new EntityNotFoundException("Entity not found for id: " + settingsDTO.getId()));
        }
    }

    /**
     * {@inheritDoc}
     */
    public Settings settingsDTOToEntity(SettingsDTO settingsDTO)
    {
        // TODO verify behavior of settingsDTOToEntity
        Settings entity = this.loadSettingsFromSettingsDTO(settingsDTO);
        this.settingsDTOToEntity(settingsDTO, entity, true);
        return entity;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void settingsDTOToEntity(
        SettingsDTO source,
        Settings target,
        boolean copyIfNull)
    {
        // TODO verify behavior of settingsDTOToEntity
        super.settingsDTOToEntity(source, target, copyIfNull);
    }
}