// Generated by hibernate/SpringHibernateDaoImpl.vsl in andromda-spring-cartridge on $springUtils.date.
// license-header java merge-point
/**
 * This is only generated once! It will never be overwritten.
 * You can (and have to!) safely modify it by hand.
 */
package bw.co.roguesystems.comm.survey.question;

import bw.co.roguesystems.comm.survey.response.SurveyResponseRepository;
import jakarta.persistence.EntityNotFoundException;

import org.springframework.stereotype.Repository;

/**
 * @see Question
 */
@Repository("questionDao")
public class QuestionDaoImpl
    extends QuestionDaoBase
{
    
    public QuestionDaoImpl(
        SurveyResponseRepository surveyResponseRepository,
        QuestionRepository questionRepository
    ) {

        super(
            surveyResponseRepository,
            questionRepository
        );
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void toQuestionDTO(
        Question source,
        QuestionDTO target)
    {
        // TODO verify behavior of toQuestionDTO
        super.toQuestionDTO(source, target);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public QuestionDTO toQuestionDTO(final Question entity)
    {
        // TODO verify behavior of toQuestionDTO
        return super.toQuestionDTO(entity);
    }

    /**
     * Retrieves the entity object that is associated with the specified value object
     * from the object store. If no such entity object exists in the object store,
     * a new, blank entity is created
     */
    private Question loadQuestionFromQuestionDTO(QuestionDTO questionDTO)
    {
        if (questionDTO.getId() == null)
        {
            return  Question.Factory.newInstance();
        }
        else
        {
            return this.questionRepository.findById(questionDTO.getId())
                .orElseThrow(() -> new EntityNotFoundException("Entity not found for id: " + questionDTO.getId()));
        }
    }

    /**
     * {@inheritDoc}
     */
    public Question questionDTOToEntity(QuestionDTO questionDTO)
    {
        // TODO verify behavior of questionDTOToEntity
        Question entity = this.loadQuestionFromQuestionDTO(questionDTO);
        this.questionDTOToEntity(questionDTO, entity, true);
        return entity;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void questionDTOToEntity(
        QuestionDTO source,
        Question target,
        boolean copyIfNull)
    {
        // TODO verify behavior of questionDTOToEntity
        super.questionDTOToEntity(source, target, copyIfNull);
    }
}