// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by SpringDao.vsl in andromda-spring-cartridge on $springUtils.date. Do not modify by hand!.
//
package bw.co.roguesystems.comm.survey.question;

import bw.co.roguesystems.comm.survey.response.SurveyResponseMapper;
import java.util.Collection;
import java.util.List;
import org.mapstruct.BeanMapping;
import org.mapstruct.InheritInverseConfiguration;
import org.mapstruct.Mapper;
import org.mapstruct.MappingTarget;
import org.mapstruct.NullValuePropertyMappingStrategy;

@Mapper(
    componentModel = "spring"
    , uses = {
        SurveyResponseMapper.class    }
)
public interface QuestionMapper {
    
    /**
     * Converts this entity to an object of type {@link QuestionDTO}.
     * @param entity
     * @return QuestionDTO
     */
    QuestionDTO toQuestionDTO(Question entity);

     /**
     * Converts this DAO's entity to a Collection of instances of type {@link QuestionDTO}.
     * @param entities
     * @return Collection<QuestionDTO>     */
    List<QuestionDTO> toQuestionDTOCollection(Collection<Question> entities);

    /**
     * Converts an instance of type {@link QuestionDTO} to this DAO's entity.
     * @param questionDTO
     * @return Question
     */
    @InheritInverseConfiguration
    Question questionDTOToEntity(QuestionDTO questionDTO);

    @BeanMapping(nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
    @InheritInverseConfiguration
    void updateQuestionFromQuestionDTO(QuestionDTO questionDTO, @MappingTarget Question entity);

}