// Generated by andromda-angular cartridge (service\service.impl.ts.vsl) CAN EDIT
import { Injectable, inject } from '@angular/core';
import { Observable } from 'rxjs';
import { SimpleMessageDTO } from '@models/bw/co/roguesystems/comm/simple/simple-message-dto';
import { HttpClient } from '@angular/common/http';
import { Page } from '@models/page.model';
import { SearchObject } from '@models/search-object';

@Injectable({
  providedIn: 'root'
})
export class SimpleMessageApi {
    
    protected path = '/simple';

    private http = inject(HttpClient);

    public findById(id: string | any ): Observable<SimpleMessageDTO | any> {

        return this.http.get<SimpleMessageDTO | any>(`${this.path}/${id}`);
    }

    public getAll(): Observable<SimpleMessageDTO[] | any[]> {

        return this.http.get<SimpleMessageDTO[] | any[]>(`${this.path}`);
    }

    public getAllPaged(pageNumber: number | any , pageSize: number | any ): Observable<Page<SimpleMessageDTO> | any> {

        return this.http.get<Page<SimpleMessageDTO> | any>(`${this.path}/paged?pageNumber=${pageNumber}&pageSize=${pageSize}`);
    }

    public remove(id: string | any ): Observable<boolean | any> {

        return this.http.delete<boolean | any>(`${this.path}/${id}`);
    }

    public save(message: SimpleMessageDTO | any ): Observable<SimpleMessageDTO | any> {

        return this.http.post<SimpleMessageDTO | any>(`${this.path}`, message);
    }

    public search(criteria: string | any ): Observable<SimpleMessageDTO[] | any[]> {

        return this.http.get<SimpleMessageDTO[] | any[]>(`${this.path}/search?criteria=${criteria}`);
    }

    public sendMessage(message: SimpleMessageDTO | any ): Observable<SimpleMessageDTO | any> {

        return this.http.post<SimpleMessageDTO | any>(`${this.path}/send`, message);
    }

}
