// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by SpringWSImpl.java.vsl in andromda-webservices.
//
package bw.co.roguesystems.comm.simple;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;
import java.util.Collection;
import org.springframework.data.domain.Page;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.web.bind.annotation.RestController;

import bw.co.roguesystems.comm.AuditTracker;

@RestController
@Tag(name = "Simple Messages", description = "Simple messages that are from one source to multiple sources with simple text. Suitable for sms or plain whatsapp.")
public class SimpleMessageApiImpl implements SimpleMessageApi {
        protected final SimpleMessageService simpleMessageService;
    
    public SimpleMessageApiImpl(
        SimpleMessageService simpleMessageService    ) {
        
        this.simpleMessageService = simpleMessageService;
    }



    @Override
    @Operation(summary = "Find Document Type", description = "Get the document type with the given id")
    public ResponseEntity<SimpleMessageDTO> findById(String id) throws Exception {
        try {
            return ResponseEntity.ok(simpleMessageService.findById(id));
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }


    @Override
    public ResponseEntity<Collection<SimpleMessageDTO>> getAll() throws Exception {
        try {
            return ResponseEntity.ok(simpleMessageService.getAll());
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }


    @Override
    public ResponseEntity<Page<SimpleMessageDTO>> getAllPaged(Integer pageNumber, Integer pageSize) throws Exception {
        try {
            return ResponseEntity.ok(simpleMessageService.getAll(pageNumber, pageSize));
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }


    @Override
    public ResponseEntity<Boolean> remove(String id) throws Exception {
        try {
            return ResponseEntity.ok(simpleMessageService.remove(id));
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }


    @Override
    public ResponseEntity<SimpleMessageDTO> save(SimpleMessageDTO message) throws Exception {
        try {
            Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
            AuditTracker.auditTrail(message, authentication);
            return ResponseEntity.ok(simpleMessageService.save(message));
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }


    @Override
    public ResponseEntity<Collection<SimpleMessageDTO>> search(String criteria) throws Exception {
        try {
            return ResponseEntity.ok(simpleMessageService.search(criteria));
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }

    @Override
    public ResponseEntity<SimpleMessageDTO> sendMessage(SimpleMessageDTO arg0) throws Exception {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'sendMessage'");
    }
    
    /**
     * Gets the reference to <code>$serviceRef.daoName</code>.
     * @return simpleMessageService
     */
    protected SimpleMessageService getSimpleMessageService()
    {
        return this.simpleMessageService;
    }
}