// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by SpringWSImpl.java.vsl in andromda-webservices.
//
package bw.co.roguesystems.comm.email;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;
import java.util.Collection;
import org.springframework.data.domain.Page;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.web.bind.annotation.RestController;

import bw.co.roguesystems.comm.AuditTracker;

@RestController
@Tag(name = "Email Messages", description = "Managing email messages. An email message is an extension on the simple message.")
public class EmailMessageApiImpl implements EmailMessageApi {
        protected final EmailMessageService emailMessageService;
    
    public EmailMessageApiImpl(
        EmailMessageService emailMessageService    ) {
        
        this.emailMessageService = emailMessageService;
    }



    @Override
    @Operation(summary = "Find Document Type", description = "Get the document type with the given id")
    public ResponseEntity<EmailMessageDTO> findById(String id) throws Exception {
        try {
            return ResponseEntity.ok(emailMessageService.findById(id));
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }


    @Override
    public ResponseEntity<Collection<EmailMessageDTO>> getAll() throws Exception {
        try {
            return ResponseEntity.ok(emailMessageService.getAll());
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }


    @Override
    public ResponseEntity<Page<EmailMessageDTO>> getAllPaged(Integer pageNumber, Integer pageSize) throws Exception {
        try {
            return ResponseEntity.ok(emailMessageService.getAll(pageNumber, pageSize));
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }


    @Override
    public ResponseEntity<Boolean> remove(String id) throws Exception {
        try {
            return ResponseEntity.ok(emailMessageService.remove(id));
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }


    @Override
    public ResponseEntity<EmailMessageDTO> save(EmailMessageDTO emailMessage) throws Exception {
        try {
            Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
            AuditTracker.auditTrail(emailMessage, authentication);
            return ResponseEntity.ok(emailMessageService.save(emailMessage));
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }


    @Override
    public ResponseEntity<Collection<EmailMessageDTO>> search(String criteria) throws Exception {
        try {
            return ResponseEntity.ok(emailMessageService.search(criteria));
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }
    @Override
    public ResponseEntity<EmailMessageDTO> sendEmail(EmailMessageDTO emailMessage) throws Exception {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'sendEmail'");
    }
    
    /**
     * Gets the reference to <code>$serviceRef.daoName</code>.
     * @return emailMessageService
     */
    protected EmailMessageService getEmailMessageService()
    {
        return this.emailMessageService;
    }

}