// Generated by andromda-angular cartridge (usecase\use-case.ts.vsl) DO NOT EDIT
import { OnInit, inject, Component, AfterViewInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { SettingsControllerImpl } from '@controllers/settings/settings-controller-impl';
import { UseCaseScope } from '@app/utils/use-case-scope';

@Component({
  selector: 'app-settings',
  templateUrl: './settings.html',
  styleUrls: ['./settings.scss'],
  standalone: true,
  imports: [
  ],
})
export class SettingsComponent implements OnInit, AfterViewInit {

    protected route: ActivatedRoute = inject(ActivatedRoute);
    protected router: Router = inject(Router);
    settingsController: SettingsControllerImpl = inject(SettingsControllerImpl);

    constructor() {
    }
	
    ngOnInit() {
    }

    ngAfterViewInit() {
    }

}