// Generated by andromda-angular cartridge (usecase\use-case.ts.vsl) DO NOT EDIT
import { 
    OnInit, 
    inject, 
    Component, 
    AfterViewInit,
    signal,
    Signal,
} from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { SettingsControllerImpl } from '@controllers/settings/settings-controller-impl';
import { UseCaseScope } from '@app/utils/use-case-scope';
import { SettingsApi } from '@services/bw/co/roguesystems/comm/settings/settings-api';
import { SettingsApiStore } from '@store/bw/co/roguesystems/comm/settings/settings-api.store';

@Component({
  selector: 'app-settings',
  templateUrl: './settings.html',
  styleUrls: ['./settings.scss'],
  standalone: true,
  imports: [
  ],
})
export class SettingsComponent implements OnInit, AfterViewInit {

    protected route: ActivatedRoute = inject(ActivatedRoute);
    protected router: Router = inject(Router);
    settingsController: SettingsControllerImpl = inject(SettingsControllerImpl);
    readonly settingsApi = inject(SettingsApi);
    readonly settingsApiStore = inject(SettingsApiStore);
    loaderMessage: Signal<string> = signal('');
    messages: Signal<string[]> = signal([]);
    success: Signal<boolean> = signal(false);
    loading: Signal<boolean> = signal(false);
    error: Signal<boolean> = signal(false);
    selected: Signal<any> = signal(null);

    constructor() {
    }
	
    ngOnInit() {
    }

    ngAfterViewInit() {
    }

}