// Generated by andromda-angular cartridge (usecase\use-case-routing.module.ts.vsl) DO NOT EDIT
import { importProvidersFrom } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';

import { SettingsComponent } from '@views/settings/settings';

import { AuthenticationGuard } from '@app/auth/authentication.guard';

import { SettingsControllerImpl } from '@controllers/settings/settings-controller-impl';
import { SettingsApi } from '@services/bw/co/roguesystems/comm/settings/settings-api';

export const routes: Routes = [
  { 
      path: '', 
      component: SettingsComponent, 
      canActivate: [AuthenticationGuard],
      data: { title: 'Settings' },
      providers: [
        SettingsControllerImpl,
        SettingsApi,
      ] 
  },
];

