// Generated by andromda-angular cartridge (service\service.impl.ts.vsl) CAN EDIT
import { Injectable, inject } from '@angular/core';
import { Observable } from 'rxjs';
import { SurveyResponseDTO } from '@models/bw/co/roguesystems/comm/survey/response/survey-response-dto';
import { HttpClient } from '@angular/common/http';
import { Page } from '@models/page.model';
import { SearchObject } from '@models/search-object';

@Injectable({
  providedIn: 'root'
})
export class SurveyResponseApi {
    
    protected path = '/survey-response';

    private http = inject(HttpClient);

    public findById(id: string | any ): Observable<SurveyResponseDTO | any> {

        return this.http.get<SurveyResponseDTO | any>(`${this.path}/${id}`);
    }

    public getAll(): Observable<SurveyResponseDTO[] | any[]> {

        return this.http.get<SurveyResponseDTO[] | any[]>(`${this.path}`);
    }

    public getAllPaged(pageNumber: number | any , pageSize: number | any ): Observable<Page<SurveyResponseDTO> | any> {

        return this.http.get<Page<SurveyResponseDTO> | any>(`${this.path}/paged?pageNumber=${pageNumber}&pageSize=${pageSize}`);
    }

    public getBySession(sessionId: string | any ): Observable<SurveyResponseDTO[] | any[]> {

        return this.http.get<SurveyResponseDTO[] | any[]>(`${this.path}/session/${sessionId}`);
    }

    public getBySessionPaged(sessionId: string | any , pageNumber: number | any , pageSize: number | any ): Observable<Page<SurveyResponseDTO> | any> {

        return this.http.get<Page<SurveyResponseDTO> | any>(`${this.path}/session/${sessionId}/paged?pageNumber=${pageNumber}&pageSize=${pageSize}`);
    }

    public getBySessionReference(sessionReference: string | any ): Observable<SurveyResponseDTO[] | any[]> {

        return this.http.get<SurveyResponseDTO[] | any[]>(`${this.path}/session-ref/${sessionReference}`);
    }

    public getBySessionReferencePaged(sessionReference: string | any , pageNumber: number | any , pageSize: number | any ): Observable<Page<SurveyResponseDTO> | any> {

        return this.http.get<Page<SurveyResponseDTO> | any>(`${this.path}/session-ref/${sessionReference}/paged?pageNumber=${pageNumber}&pageSize=${pageSize}`);
    }

    public remove(id: string | any ): Observable<boolean | any> {

        return this.http.delete<boolean | any>(`${this.path}/${id}`);
    }

    public save(response: SurveyResponseDTO | any ): Observable<SurveyResponseDTO | any> {

        return this.http.post<SurveyResponseDTO | any>(`${this.path}`, response);
    }

    public search(criteria: string | any ): Observable<SurveyResponseDTO[] | any[]> {

        return this.http.get<SurveyResponseDTO[] | any[]>(`${this.path}/search?criteria=${criteria}`);
    }

}
