// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by SpringWSImpl.java.vsl in andromda-webservices.
//
package bw.co.roguesystems.comm.survey;

import bw.co.roguesystems.comm.AuditTracker;
import bw.co.roguesystems.comm.survey.question.QuestionDTO;
import bw.co.roguesystems.comm.survey.question.QuestionService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;
import java.util.Collection;
import java.util.Set;

import org.springframework.data.domain.Page;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.web.bind.annotation.RestController;

@RestController
@Tag(name = "Surveys Setups", description = "Setups of surveys including the questions to be responded to.")
public class SurveyApiImpl implements SurveyApi {
        protected final SurveyService surveyService;
        protected final QuestionService questionService;
    
    public SurveyApiImpl(
        SurveyService surveyService,        QuestionService questionService    ) {
        
        this.surveyService = surveyService;
        this.questionService = questionService;
    }



    @Override
    @Operation(summary = "Add Question to Survey", description = "Add the given question to the survey specified by the id.")
    public ResponseEntity<SurveyDTO> addQuestion(String id, QuestionDTO question) throws Exception {
        try {
            return ResponseEntity.ok(surveyService.addQuestion(id, question));
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }


    @Override
    @Operation(summary = "Find Document Type", description = "Get the document type with the given id")
    public ResponseEntity<SurveyDTO> findById(String id) throws Exception {
        try {
            return ResponseEntity.ok(surveyService.findById(id));
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }


    @Override
    @Operation(summary = "Find Session By Reference", description = "Get session by the given reference")
    public ResponseEntity<SurveyDTO> findByReference(String reference) throws Exception {
        try {
            return ResponseEntity.ok(surveyService.findByReference(reference));
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }


    @Override
    public ResponseEntity<Collection<SurveyDTO>> getAll() throws Exception {
        try {
            return ResponseEntity.ok(surveyService.getAll());
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }


    @Override
    public ResponseEntity<Page<SurveyDTO>> getAllPaged(Integer pageNumber, Integer pageSize) throws Exception {
        try {
            return ResponseEntity.ok(surveyService.getAll(pageNumber, pageSize));
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }


    @Override
    public ResponseEntity<Boolean> remove(String id) throws Exception {
        try {
            return ResponseEntity.ok(surveyService.remove(id));
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }


    @Override
    @Operation(summary = "Add Question to Survey", description = "Add the given question to the survey specified by the id.")
    public ResponseEntity<SurveyDTO> removeQuestion(String id, String questionId) throws Exception {
        try {
            return ResponseEntity.ok(null);
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }


    @Override
    public ResponseEntity<SurveyDTO> save(SurveyDTO message) throws Exception {
        try {
            Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
            AuditTracker.auditTrail(message, authentication);
            return ResponseEntity.ok(surveyService.save(message));
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }


    @Override
    public ResponseEntity<Collection<SurveyDTO>> search(String criteria) throws Exception {
        try {
            return ResponseEntity.ok(surveyService.search(criteria));
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }
    
    /**
     * Gets the reference to <code>$serviceRef.daoName</code>.
     * @return surveyService
     */
    protected SurveyService getSurveyService()
    {
        return this.surveyService;
    }
    
    /**
     * Gets the reference to <code>$serviceRef.daoName</code>.
     * @return questionService
     */
    protected QuestionService getQuestionService()
    {
        return this.questionService;
    }



    @Override
    public ResponseEntity<SurveyDTO> launch(String id, Set<String> destinations) throws Exception {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'launch'");
    }
}