// Generated by andromda-angular cartridge (service\service.impl.ts.vsl) CAN EDIT
import { Injectable, inject } from '@angular/core';
import { Observable } from 'rxjs';
import { CommMessageDTO } from '@models/bw/co/roguesystems/comm/message/comm-message-dto';
import { HttpClient } from '@angular/common/http';
import { Page } from '@models/page.model';
import { SearchObject } from '@models/search-object';

@Injectable({
  providedIn: 'root'
})
export class CommMessageApi {
    
    protected path = '/message';

    private http = inject(HttpClient);

    public findById(id: string | any ): Observable<CommMessageDTO | any> {

        return this.http.get<CommMessageDTO | any>(`${this.path}/${id}`);
    }

    public getAll(): Observable<CommMessageDTO[] | any[]> {

        return this.http.get<CommMessageDTO[] | any[]>(`${this.path}`);
    }

    public getAllPaged(pageNumber: number | any , pageSize: number | any ): Observable<Page<CommMessageDTO> | any> {

        return this.http.get<Page<CommMessageDTO> | any>(`${this.path}/paged?pageNumber=${pageNumber}&pageSize=${pageSize}`);
    }

    public remove(id: string | any ): Observable<boolean | any> {

        return this.http.delete<boolean | any>(`${this.path}/${id}`);
    }

    public save(message: CommMessageDTO | any ): Observable<CommMessageDTO | any> {

        return this.http.post<CommMessageDTO | any>(`${this.path}`, message);
    }

    public search(criteria: string | any ): Observable<CommMessageDTO[] | any[]> {

        return this.http.get<CommMessageDTO[] | any[]>(`${this.path}/search?criteria=${criteria}`);
    }

    public sendMessage(messages: CommMessageDTO | any ): Observable<CommMessageDTO[] | any[]> {

        return this.http.post<CommMessageDTO[] | any[]>(`${this.path}/send`, messages);
    }

}
