// Generated by hibernate/SpringHibernateDaoImpl.vsl in andromda-spring-cartridge on $springUtils.date.
// license-header java merge-point
/**
 * This is only generated once! It will never be overwritten.
 * You can (and have to!) safely modify it by hand.
 */
package bw.co.roguesystems.comm.survey;

import bw.co.roguesystems.comm.session.SessionRepository;
import bw.co.roguesystems.comm.survey.question.QuestionRepository;
import jakarta.persistence.EntityNotFoundException;

import org.springframework.stereotype.Repository;

/**
 * @see Survey
 */
@Repository("surveyDao")
public class SurveyDaoImpl
    extends SurveyDaoBase
{
    
    public SurveyDaoImpl(
        QuestionRepository questionRepository,
        SessionRepository sessionRepository,
        SurveyRepository surveyRepository
    ) {

        super(
            questionRepository,
            sessionRepository,
            surveyRepository
        );
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void toSurveyDTO(
        Survey source,
        SurveyDTO target)
    {
        // TODO verify behavior of toSurveyDTO
        super.toSurveyDTO(source, target);
        // WARNING! No conversion for target.questions (can't convert source.getQuestions():bw.co.roguesystems.comm.survey.question.Question to bw.co.roguesystems.comm.survey.question.QuestionDTO
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SurveyDTO toSurveyDTO(final Survey entity)
    {
        // TODO verify behavior of toSurveyDTO
        return super.toSurveyDTO(entity);
    }

    /**
     * Retrieves the entity object that is associated with the specified value object
     * from the object store. If no such entity object exists in the object store,
     * a new, blank entity is created
     */
    private Survey loadSurveyFromSurveyDTO(SurveyDTO surveyDTO)
    {
        if (surveyDTO.getId() == null)
        {
            return  Survey.Factory.newInstance();
        }
        else
        {
            return this.surveyRepository.findById(surveyDTO.getId())
                .orElseThrow(() -> new EntityNotFoundException("Entity not found for id: " + surveyDTO.getId()));
        }
    }

    /**
     * {@inheritDoc}
     */
    public Survey surveyDTOToEntity(SurveyDTO surveyDTO)
    {
        // TODO verify behavior of surveyDTOToEntity
        Survey entity = this.loadSurveyFromSurveyDTO(surveyDTO);
        this.surveyDTOToEntity(surveyDTO, entity, true);
        return entity;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void surveyDTOToEntity(
        SurveyDTO source,
        Survey target,
        boolean copyIfNull)
    {
        // TODO verify behavior of surveyDTOToEntity
        super.surveyDTOToEntity(source, target, copyIfNull);
    }
}