// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by SpringDao.vsl in andromda-spring-cartridge on $springUtils.date. Do not modify by hand!.
//
package bw.co.roguesystems.comm.survey;

import bw.co.roguesystems.comm.session.SessionMapper;
import bw.co.roguesystems.comm.survey.question.QuestionMapper;
import java.util.Collection;
import java.util.List;
import org.mapstruct.BeanMapping;
import org.mapstruct.InheritInverseConfiguration;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingTarget;
import org.mapstruct.NullValuePropertyMappingStrategy;

@Mapper(
    componentModel = "spring"
    , uses = {
        QuestionMapper.class,
        SessionMapper.class    }
)
public interface SurveyMapper {
    
    /**
     * Converts this entity to an object of type {@link SurveyDTO}.
     * @param entity
     * @return SurveyDTO
     */
    @Mapping(source = "questions", target = "questions")
    SurveyDTO toSurveyDTO(Survey entity);

     /**
     * Converts this DAO's entity to a Collection of instances of type {@link SurveyDTO}.
     * @param entities
     * @return Collection<SurveyDTO>     */
    List<SurveyDTO> toSurveyDTOCollection(Collection<Survey> entities);

    /**
     * Converts an instance of type {@link SurveyDTO} to this DAO's entity.
     * @param surveyDTO
     * @return Survey
     */
    @InheritInverseConfiguration
    Survey surveyDTOToEntity(SurveyDTO surveyDTO);

    @BeanMapping(nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
    @InheritInverseConfiguration
    void updateSurveyFromSurveyDTO(SurveyDTO surveyDTO, @MappingTarget Survey entity);

}