// Generated by andromda-angular cartridge (controller\controller.impl.ts.vsl) Can Modify
import { Injectable } from '@angular/core';
import { SurveyController } from '@controllers/survey/survey-controller';

@Injectable()
export class SurveyControllerImpl extends SurveyController {

    constructor() {
        super();
    }

}
