// Generated by andromda-angular cartridge (service\service.impl.ts.vsl) CAN EDIT
import { Injectable, inject } from '@angular/core';
import { Observable } from 'rxjs';
import { EmailMessageDTO } from '@models/bw/co/roguesystems/comm/email/email-message-dto';
import { HttpClient } from '@angular/common/http';
import { Page } from '@models/page.model';
import { SearchObject } from '@models/search-object';

@Injectable({
  providedIn: 'root'
})
export class EmailMessageApi {
    
    protected path = '/email';

    private http = inject(HttpClient);

    public findById(id: string | any ): Observable<EmailMessageDTO | any> {

        return this.http.get<EmailMessageDTO | any>(`${this.path}/${id}`);
    }

    public getAll(): Observable<EmailMessageDTO[] | any[]> {

        return this.http.get<EmailMessageDTO[] | any[]>(`${this.path}`);
    }

    public getAllPaged(pageNumber: number | any , pageSize: number | any ): Observable<Page<EmailMessageDTO> | any> {

        return this.http.get<Page<EmailMessageDTO> | any>(`${this.path}/paged?pageNumber=${pageNumber}&pageSize=${pageSize}`);
    }

    public remove(id: string | any ): Observable<boolean | any> {

        return this.http.delete<boolean | any>(`${this.path}/${id}`);
    }

    public save(emailMessage: EmailMessageDTO | any ): Observable<EmailMessageDTO | any> {

        return this.http.post<EmailMessageDTO | any>(`${this.path}`, emailMessage);
    }

    public search(criteria: string | any ): Observable<EmailMessageDTO[] | any[]> {

        return this.http.get<EmailMessageDTO[] | any[]>(`${this.path}/search?criteria=${criteria}`);
    }

    public sendEmail(emailMessage: EmailMessageDTO | any ): Observable<EmailMessageDTO | any> {

        return this.http.post<EmailMessageDTO | any>(`${this.path}/send`, emailMessage);
    }

}
