// license-header angular merge-point
//
/**
 * @author Generated by app-routing.module.ts.vsl in andromda-anglar-cartridge Do not modify by hand!
 *
 * MODEL CLASS:  $validationName
 */
import { Routes } from '@angular/router';
import { Shell } from '@app/shell/shell';
import { UseCaseScope } from './utils/use-case-scope';

export const routes: Routes = [
  Shell.childRoutes([
    {
      path: '',
      data: { title: 'Home' },
      loadComponent: () => import('./views/home/home').then((c) => c.Home),
    },
    {
      path: 'about',
      data: { title: 'About' },
      loadComponent: () => import('./views/about/about').then((c) => c.About),
    },
    {
      path: 'surveys', 
      loadChildren: () => import('@views/survey/surveys.routes').then((m) => m.routes),
      providers: [
        UseCaseScope
      ]
    },
    {
      path: 'settings', 
      loadChildren: () => import('@views/settings/settings.routes').then((m) => m.routes),
      providers: [
        UseCaseScope
      ]
    },
  ]),
  // Fallback when no prior route is matched
  { 
    path: '**', redirectTo: '', pathMatch: 'full' 
  },
];
