// license-header angular merge-point
//
/**
 * @author Generated by app-routing.module.ts.vsl in andromda-anglar-cartridge Do not modify by hand!
 *
 * MODEL CLASS:  $validationName
 */
import { Routes } from '@angular/router';
import { Shell } from './shell';
// import { LoginComponent } from './auth/login.component';
import { surveysRoutes } from '@app/views/survey/surveys.routes';
import { settingsRoutes } from '@app/views/settings/settings.routes';

export const routes: Routes = [
  // Uncomment the following lines to enable login route
  //{
  //  path: 'login',
  //  component: LoginComponent,
  //},
  Shell.childRoutes([
    {
      path: '',
      data: { title: 'Home' },
      loadComponent: () => import('./views/home/home').then((m) => m.Home),
    },
    {
      path: 'about',
      data: { title: 'About' },
      loadComponent: () => import('./views/about/about').then((m) => m.About),
    },
    ...surveysRoutes,
    ...settingsRoutes,
  ]),
  // Fallback when no prior route is matched
  { 
    path: '**', redirectTo: '', pathMatch: 'full' 
  },
];
