// Generated by andromda-angular cartridge (service\service.impl.ts.vsl) CAN EDIT
import { Injectable, inject } from '@angular/core';
import { Observable } from 'rxjs';
import { SessionDTO } from '@models/bw/co/roguesystems/comm/session/session-dto';
import { HttpClient } from '@angular/common/http';
import { Page } from '@models/page.model';
import { SearchObject } from '@models/search-object';

@Injectable({
  providedIn: 'root'
})
export class SessionApi {
    
    protected path = '/session';

    private http = inject(HttpClient);

    public findById(id: string | any ): Observable<SessionDTO | any> {

        return this.http.get<SessionDTO | any>(`${this.path}/${id}`);
    }

    public findByReference(reference: string | any ): Observable<SessionDTO | any> {

        return this.http.get<SessionDTO | any>(`${this.path}/reference/${reference}`);
    }

    public getAll(): Observable<SessionDTO[] | any[]> {

        return this.http.get<SessionDTO[] | any[]>(`${this.path}`);
    }

    public getAllPaged(pageNumber: number | any , pageSize: number | any ): Observable<Page<SessionDTO> | any> {

        return this.http.get<Page<SessionDTO> | any>(`${this.path}/paged?pageNumber=${pageNumber}&pageSize=${pageSize}`);
    }

    public getBySurvey(surveyId: string | any ): Observable<SessionDTO[] | any[]> {

        return this.http.get<SessionDTO[] | any[]>(`${this.path}/survey/${surveyId}`);
    }

    public getBySurveyPaged(surveyId: string | any , pageNumber: number | any , pageSize: number | any ): Observable<Page<SessionDTO> | any> {

        return this.http.get<Page<SessionDTO> | any>(`${this.path}/survey/${surveyId}/paged?pageNumber=${pageNumber}&pageSize=${pageSize}`);
    }

    public getBySurveyReference(surveyReference: string | any ): Observable<SessionDTO[] | any[]> {

        return this.http.get<SessionDTO[] | any[]>(`${this.path}/survey-ref/${surveyReference}`);
    }

    public getBySurveyReferencePaged(surveyReference: string | any , pageNumber: number | any , pageSize: number | any ): Observable<Page<SessionDTO> | any> {

        return this.http.get<Page<SessionDTO> | any>(`${this.path}/survey-ref/${surveyReference}/paged?pageNumber=${pageNumber}&pageSize=${pageSize}`);
    }

    public next(reference: string | any ): Observable<SessionDTO | any> {

        return this.http.get<SessionDTO | any>(`${this.path}/next/${reference}`);
    }

    public remove(id: string | any ): Observable<boolean | any> {

        return this.http.delete<boolean | any>(`${this.path}/${id}`);
    }

    public save(session: SessionDTO | any ): Observable<SessionDTO | any> {

        return this.http.post<SessionDTO | any>(`${this.path}`, session);
    }

    public search(criteria: string | any ): Observable<SessionDTO[] | any[]> {

        return this.http.get<SessionDTO[] | any[]>(`${this.path}/search?criteria=${criteria}`);
    }

}
