// Generated by andromda-angular cartridge (service\service.impl.ts.vsl) CAN EDIT
import { Injectable, inject } from '@angular/core';
import { Observable } from 'rxjs';
import { QuestionDTO } from '@models/bw/co/roguesystems/comm/survey/question/question-dto';
import { SurveyDTO } from '@models/bw/co/roguesystems/comm/survey/survey-dto';
import { HttpClient } from '@angular/common/http';
import { Page } from '@models/page.model';
import { SearchObject } from '@models/search-object';

@Injectable({
  providedIn: 'root'
})
export class SurveyApi {
    
    protected path = '/survey';

    private http = inject(HttpClient);

    public addQuestion(id: string | any , question: QuestionDTO | any ): Observable<SurveyDTO | any> {

        return this.http.post<SurveyDTO | any>(`${this.path}/${id}/question`, {id: id, question: question});
    }

    public findById(id: string | any ): Observable<SurveyDTO | any> {

        return this.http.get<SurveyDTO | any>(`${this.path}/${id}`);
    }

    public findByReference(reference: string | any ): Observable<SurveyDTO | any> {

        return this.http.get<SurveyDTO | any>(`${this.path}/reference/${reference}`);
    }

    public getAll(): Observable<SurveyDTO[] | any[]> {

        return this.http.get<SurveyDTO[] | any[]>(`${this.path}`);
    }

    public getAllPaged(pageNumber: number | any , pageSize: number | any ): Observable<Page<SurveyDTO> | any> {

        return this.http.get<Page<SurveyDTO> | any>(`${this.path}/paged?pageNumber=${pageNumber}&pageSize=${pageSize}`);
    }

    public remove(id: string | any ): Observable<boolean | any> {

        return this.http.delete<boolean | any>(`${this.path}/${id}`);
    }

    public removeQuestion(id: string | any , questionId: string | any ): Observable<SurveyDTO | any> {

        return this.http.delete<SurveyDTO | any>(`${this.path}/${id}/question/${questionId}`);
    }

    public save(message: SurveyDTO | any ): Observable<SurveyDTO | any> {

        return this.http.post<SurveyDTO | any>(`${this.path}`, message);
    }

    public search(criteria: string | any ): Observable<SurveyDTO[] | any[]> {

        return this.http.get<SurveyDTO[] | any[]>(`${this.path}/search?criteria=${criteria}`);
    }

}
