// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by SpringDao.vsl in andromda-spring-cartridge on $springUtils.date. Do not modify by hand!.
//
package bw.co.roguesystems.comm.sequence;

import org.mapstruct.Mapper;

@Mapper(
    componentModel = "spring"
    , uses = {
        SequencePartMapper.class    }
)
public interface SequenceGeneratorMapper {
    
}