// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by SpringWSImpl.java.vsl in andromda-webservices.
//
package bw.co.roguesystems.comm.message;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;
import java.util.Collection;
import java.util.Set;
import org.springframework.data.domain.Page;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.web.bind.annotation.RestController;

import bw.co.roguesystems.comm.AuditTracker;

@RestController
@Tag(name = "Communication Messages", description = "Communication messages. Should handl all three message types.")
public class CommMessageApiImpl implements CommMessageApi {
        protected final CommMessageService commMessageService;
    
    public CommMessageApiImpl(
        CommMessageService commMessageService    ) {
        
        this.commMessageService = commMessageService;
    }



    @Override
    @Operation(summary = "Find Document Type", description = "Get the document type with the given id")
    public ResponseEntity<CommMessageDTO> findById(String id) throws Exception {
        try {
            return ResponseEntity.ok(commMessageService.findById(id));
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }


    @Override
    public ResponseEntity<Collection<CommMessageDTO>> getAll() throws Exception {
        try {
            return ResponseEntity.ok(commMessageService.getAll());
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }


    @Override
    public ResponseEntity<Page<CommMessageDTO>> getAllPaged(Integer pageNumber, Integer pageSize) throws Exception {
        try {
            return ResponseEntity.ok(commMessageService.getAll(pageNumber, pageSize));
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }


    @Override
    public ResponseEntity<Boolean> remove(String id) throws Exception {
        try {
            return ResponseEntity.ok(commMessageService.remove(id));
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }


    @Override
    public ResponseEntity<CommMessageDTO> save(CommMessageDTO message) throws Exception {
        try {
            Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
            AuditTracker.auditTrail(message, authentication);
            return ResponseEntity.ok(commMessageService.save(message));
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }


    @Override
    public ResponseEntity<Collection<CommMessageDTO>> search(String criteria) throws Exception {
        try {
            return ResponseEntity.ok(commMessageService.search(criteria));
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }


    @Override
    public ResponseEntity<Collection<CommMessageDTO>> sendMessage(Set<CommMessageDTO> messages) throws Exception {
        try {
            for (CommMessageDTO message : messages) {
                Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
                AuditTracker.auditTrail(message, authentication);
            }
            return ResponseEntity.ok(commMessageService.sendMessage(messages));
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }
    
    /**
     * Gets the reference to <code>$serviceRef.daoName</code>.
     * @return commMessageService
     */
    protected CommMessageService getCommMessageService()
    {
        return this.commMessageService;
    }
}