// Generated by hibernate/SpringHibernateDaoImpl.vsl in andromda-spring-cartridge on $springUtils.date.
// license-header java merge-point
/**
 * This is only generated once! It will never be overwritten.
 * You can (and have to!) safely modify it by hand.
 */
package bw.co.roguesystems.comm.email;

import org.springframework.stereotype.Repository;

import jakarta.persistence.EntityNotFoundException;

/**
 * @see EmailMessage
 */
@Repository("emailMessageDao")
public class EmailMessageDaoImpl
    extends EmailMessageDaoBase
{
    
    public EmailMessageDaoImpl(
        EmailMessageRepository emailMessageRepository
    ) {

        super(
            emailMessageRepository
        );
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void toEmailMessageDTO(
        EmailMessage source,
        EmailMessageDTO target)
    {
        // TODO verify behavior of toEmailMessageDTO
        super.toEmailMessageDTO(source, target);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EmailMessageDTO toEmailMessageDTO(final EmailMessage entity)
    {
        // TODO verify behavior of toEmailMessageDTO
        return super.toEmailMessageDTO(entity);
    }

    /**
     * Retrieves the entity object that is associated with the specified value object
     * from the object store. If no such entity object exists in the object store,
     * a new, blank entity is created
     */
    private EmailMessage loadEmailMessageFromEmailMessageDTO(EmailMessageDTO emailMessageDTO)
    {
        if (emailMessageDTO.getId() == null)
        {
            return  EmailMessage.Factory.newInstance();
        }
        else
        {
            return this.emailMessageRepository.findById(emailMessageDTO.getId())
                .orElseThrow(() -> new EntityNotFoundException("Entity not found for id: " + emailMessageDTO.getId()));
        }
    }

    /**
     * {@inheritDoc}
     */
    public EmailMessage emailMessageDTOToEntity(EmailMessageDTO emailMessageDTO)
    {
        // TODO verify behavior of emailMessageDTOToEntity
        EmailMessage entity = this.loadEmailMessageFromEmailMessageDTO(emailMessageDTO);
        this.emailMessageDTOToEntity(emailMessageDTO, entity, true);
        return entity;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void emailMessageDTOToEntity(
        EmailMessageDTO source,
        EmailMessage target,
        boolean copyIfNull)
    {
        // TODO verify behavior of emailMessageDTOToEntity
        super.emailMessageDTOToEntity(source, target, copyIfNull);
    }
}