// Generated by andromda-angular cartridge (usecase\use-case.ts.vsl) DO NOT EDIT
import { 
    OnInit, 
    inject, 
    Component, 
    AfterViewInit,
    signal,
    Signal,
} from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { SurveyControllerImpl } from '@controllers/survey/survey-controller-impl';
import { UseCaseScope } from '@app/utils/use-case-scope';

@Component({
  selector: 'app-surveys',
  templateUrl: './surveys.html',
  styleUrls: ['./surveys.scss'],
  standalone: true,
  imports: [
  ],
})
export class SurveysComponent implements OnInit, AfterViewInit {

    protected route: ActivatedRoute = inject(ActivatedRoute);
    protected router: Router = inject(Router);
    surveyController: SurveyControllerImpl = inject(SurveyControllerImpl);
    loaderMessage: Signal<string> = signal('');
    messages: Signal<string[]> = signal([]);
    success: Signal<boolean> = signal(false);
    loading: Signal<boolean> = signal(false);
    error: Signal<boolean> = signal(false);
    selected: Signal<any> = signal(null);

    constructor() {
    }
	
    ngOnInit() {
    }

    ngAfterViewInit() {
    }

}