// Generated by andromda-angular cartridge (usecase\use-case-routing.module.ts.vsl) DO NOT EDIT
import { importProvidersFrom } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';

import { SurveysComponent } from '@views/survey/surveys';

import { AuthenticationGuard } from '@app/auth/authentication.guard';

import { OrganisationControllerImpl } from '@controllers/survey/organisation-controller-impl';

export const routes: Routes = [
  { 
      path: '', 
      component: SurveysComponent, 
      canActivate: [AuthenticationGuard],
      data: { title: 'Surveys' },
      providers: [
        OrganisationControllerImpl,
      ] 
  },
];

