// Generated by andromda-angular cartridge (usecase\use-case.ts.vsl) DO NOT EDIT
import { OnInit, inject, Component, AfterViewInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { OrganisationControllerImpl } from '@controllers/survey/organisation-controller-impl';
import { UseCaseScope } from '@app/utils/use-case-scope';

@Component({
  selector: 'app-surveys',
  templateUrl: './surveys.html',
  styleUrls: ['./surveys.scss'],
  standalone: true,
  imports: [],
})
export class SurveysComponent implements OnInit, AfterViewInit {

    protected route: ActivatedRoute = inject(ActivatedRoute);
    protected router: Router = inject(Router);

    constructor() {
    }
	
    ngOnInit() {
        
    }

    ngAfterViewInit() {
    }

}