// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by SpringWSImpl.java.vsl in andromda-webservices.
//
package bw.co.roguesystems.comm.settings;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;
import java.util.Collection;
import org.springframework.data.domain.Page;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RestController;

@RestController
@Tag(name = "System Settings", description = "Managing system settings.")
public class SettingsApiImpl implements SettingsApi {
        protected final SettingsService settingsService;
    
    public SettingsApiImpl(
        SettingsService settingsService    ) {
        
        this.settingsService = settingsService;
    }


    @Override
    @Operation(summary = "Find Document Type", description = "Get the document type with the given id")
    public ResponseEntity<SettingsDTO> findById(String id) throws Exception {
        try {
            return ResponseEntity.ok(settingsService.findById(id));
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }

    @Override
    public ResponseEntity<Collection<SettingsDTO>> getAll() throws Exception {
        try {
            return ResponseEntity.ok(settingsService.getAll());
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }


    @Override
    public ResponseEntity<Page<SettingsDTO>> getAllPaged(Integer pageNumber, Integer pageSize) throws Exception {
        try {
            return ResponseEntity.ok(settingsService.getAll(pageNumber, pageSize));
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }


    @Override
    public ResponseEntity<Page<SettingsDTO>> pagedSearch(String criteria, Integer pageNumber, Integer pageSize) throws Exception {
        try {
            return ResponseEntity.ok(settingsService.search(criteria, pageNumber, pageSize));
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }


    @Override
    public ResponseEntity<Boolean> remove(String id) throws Exception {
        try {
            return ResponseEntity.ok(settingsService.remove(id));
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }


    @Override
    public ResponseEntity<SettingsDTO> save(SettingsDTO setttings) throws Exception {
        try {
            return ResponseEntity.ok(settingsService.save(setttings));
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }


    @Override
    public ResponseEntity<Collection<SettingsDTO>> search(String criteria) throws Exception {
        try {
            return ResponseEntity.ok(settingsService.search(criteria));
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }
    
    /**
     * Gets the reference to <code>$serviceRef.daoName</code>.
     * @return settingsService
     */
    protected SettingsService getSettingsService()
    {
        return this.settingsService;
    }
}