// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by SpringDao.vsl in andromda-spring-cartridge on $springUtils.date. Do not modify by hand!.
//
package bw.co.roguesystems.comm.survey.response;

import bw.co.roguesystems.comm.session.SessionMapper;
import bw.co.roguesystems.comm.survey.question.QuestionMapper;
import java.util.Collection;
import java.util.List;
import org.mapstruct.BeanMapping;
import org.mapstruct.InheritInverseConfiguration;
import org.mapstruct.Mapper;
import org.mapstruct.MappingTarget;
import org.mapstruct.NullValuePropertyMappingStrategy;

@Mapper(
    componentModel = "spring"
    , uses = {
        QuestionMapper.class,
        SessionMapper.class    }
)
public interface SurveyResponseMapper {
    
    /**
     * Converts this entity to an object of type {@link SurveyResponseDTO}.
     * @param entity
     * @return SurveyResponseDTO
     */
    SurveyResponseDTO toSurveyResponseDTO(SurveyResponse entity);

     /**
     * Converts this DAO's entity to a Collection of instances of type {@link SurveyResponseDTO}.
     * @param entities
     * @return Collection<SurveyResponseDTO>     */
    List<SurveyResponseDTO> toSurveyResponseDTOCollection(Collection<SurveyResponse> entities);

    /**
     * Converts an instance of type {@link SurveyResponseDTO} to this DAO's entity.
     * @param surveyResponseDTO
     * @return SurveyResponse
     */
    @InheritInverseConfiguration
    SurveyResponse surveyResponseDTOToEntity(SurveyResponseDTO surveyResponseDTO);

    @BeanMapping(nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
    @InheritInverseConfiguration
    void updateSurveyResponseFromSurveyResponseDTO(SurveyResponseDTO surveyResponseDTO, @MappingTarget SurveyResponse entity);

}