// Generated by hibernate/SpringHibernateDaoImpl.vsl in andromda-spring-cartridge on $springUtils.date.
// license-header java merge-point
/**
 * This is only generated once! It will never be overwritten.
 * You can (and have to!) safely modify it by hand.
 */
package bw.co.roguesystems.comm.survey.response;

import bw.co.roguesystems.comm.session.SessionRepository;
import bw.co.roguesystems.comm.survey.question.QuestionRepository;
import org.springframework.stereotype.Repository;

/**
 * @see SurveyResponse
 */
@Repository("surveyResponseDao")
public class SurveyResponseDaoImpl
    extends SurveyResponseDaoBase
{
    
    public SurveyResponseDaoImpl(
        QuestionRepository questionRepository,
        SessionRepository sessionRepository,
        SurveyResponseRepository surveyResponseRepository
    ) {

        super(
            questionRepository,
            sessionRepository,
            surveyResponseRepository
        );
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void toSurveyResponseDTO(
        SurveyResponse source,
        SurveyResponseDTO target)
    {
        // TODO verify behavior of toSurveyResponseDTO
        super.toSurveyResponseDTO(source, target);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SurveyResponseDTO toSurveyResponseDTO(final SurveyResponse entity)
    {
        // TODO verify behavior of toSurveyResponseDTO
        return super.toSurveyResponseDTO(entity);
    }

    /**
     * Retrieves the entity object that is associated with the specified value object
     * from the object store. If no such entity object exists in the object store,
     * a new, blank entity is created
     */
    private SurveyResponse loadSurveyResponseFromSurveyResponseDTO(SurveyResponseDTO surveyResponseDTO)
    {
        // TODO implement loadSurveyResponseFromSurveyResponseDTO
        throw new UnsupportedOperationException("bw.co.roguesystems.comm.survey.response.loadSurveyResponseFromSurveyResponseDTO(SurveyResponseDTO) not yet implemented.");

        /* A typical implementation looks like this:
        if (surveyResponseDTO.getId() == null)
        {
            return  SurveyResponse.Factory.newInstance();
        }
        else
        {
            return this.surveyResponseRepository.findById(surveyResponseDTO.getId())
                .orElseThrow(() -> new EntityNotFoundException("Entity not found for id: " + surveyResponseDTO.getId()));
        }
        */
    }

    /**
     * {@inheritDoc}
     */
    public SurveyResponse surveyResponseDTOToEntity(SurveyResponseDTO surveyResponseDTO)
    {
        // TODO verify behavior of surveyResponseDTOToEntity
        SurveyResponse entity = this.loadSurveyResponseFromSurveyResponseDTO(surveyResponseDTO);
        this.surveyResponseDTOToEntity(surveyResponseDTO, entity, true);
        return entity;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void surveyResponseDTOToEntity(
        SurveyResponseDTO source,
        SurveyResponse target,
        boolean copyIfNull)
    {
        // TODO verify behavior of surveyResponseDTOToEntity
        super.surveyResponseDTOToEntity(source, target, copyIfNull);
    }
}