// Generated by hibernate/SpringHibernateDaoImpl.vsl in andromda-spring-cartridge on $springUtils.date.
// license-header java merge-point
/**
 * This is only generated once! It will never be overwritten.
 * You can (and have to!) safely modify it by hand.
 */
package bw.co.roguesystems.comm.simple;

import org.springframework.stereotype.Repository;

import jakarta.persistence.EntityNotFoundException;

/**
 * @see SimpleMessage
 */
@Repository("simpleMessageDao")
public class SimpleMessageDaoImpl
    extends SimpleMessageDaoBase
{
    
    public SimpleMessageDaoImpl(
        SimpleMessageRepository simpleMessageRepository
    ) {

        super(
            simpleMessageRepository
        );
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void toSimpleMessageDTO(
        SimpleMessage source,
        SimpleMessageDTO target)
    {
        // TODO verify behavior of toSimpleMessageDTO
        super.toSimpleMessageDTO(source, target);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SimpleMessageDTO toSimpleMessageDTO(final SimpleMessage entity)
    {
        // TODO verify behavior of toSimpleMessageDTO
        return super.toSimpleMessageDTO(entity);
    }

    /**
     * Retrieves the entity object that is associated with the specified value object
     * from the object store. If no such entity object exists in the object store,
     * a new, blank entity is created
     */
    private SimpleMessage loadSimpleMessageFromSimpleMessageDTO(SimpleMessageDTO simpleMessageDTO)
    {
        if (simpleMessageDTO.getId() == null)
        {
            return  SimpleMessage.Factory.newInstance();
        }
        else
        {
            return this.simpleMessageRepository.findById(simpleMessageDTO.getId())
                .orElseThrow(() -> new EntityNotFoundException("Entity not found for id: " + simpleMessageDTO.getId()));
        }
    }

    /**
     * {@inheritDoc}
     */
    public SimpleMessage simpleMessageDTOToEntity(SimpleMessageDTO simpleMessageDTO)
    {
        // TODO verify behavior of simpleMessageDTOToEntity
        SimpleMessage entity = this.loadSimpleMessageFromSimpleMessageDTO(simpleMessageDTO);
        this.simpleMessageDTOToEntity(simpleMessageDTO, entity, true);
        return entity;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void simpleMessageDTOToEntity(
        SimpleMessageDTO source,
        SimpleMessage target,
        boolean copyIfNull)
    {
        // TODO verify behavior of simpleMessageDTOToEntity
        super.simpleMessageDTOToEntity(source, target, copyIfNull);
    }
}