// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by SpringDao.vsl in andromda-spring-cartridge on $springUtils.date. Do not modify by hand!.
//
package bw.co.roguesystems.comm.session;

import bw.co.roguesystems.comm.survey.SurveyMapper;
import bw.co.roguesystems.comm.survey.question.QuestionMapper;
import bw.co.roguesystems.comm.survey.response.SurveyResponseMapper;
import java.util.Collection;
import java.util.List;
import org.mapstruct.BeanMapping;
import org.mapstruct.InheritInverseConfiguration;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingTarget;
import org.mapstruct.NullValuePropertyMappingStrategy;

@Mapper(
    componentModel = "spring"
    , uses = {
        SurveyMapper.class,
        QuestionMapper.class,
        SurveyResponseMapper.class    }
)
public interface SessionMapper {
    
    /**
     * Converts this entity to an object of type {@link SessionDTO}.
     * @param entity
     * @return SessionDTO
     */
    @Mapping(source = "nextQuestion", target = "nextQuestion")
    // WARNING! No conversion for target.survey (can't convert source.getSurvey():bw.co.roguesystems.comm.survey.Survey to java.lang.String
    @Mapping(source = "questions", target = "questions")
    @Mapping(source = "survey.name", target = "survey")
    @Mapping(source = "survey.id", target = "surveyId")
    @Mapping(source = "survey.reference", target = "surveyReference")
    SessionDTO toSessionDTO(Session entity);

     /**
     * Converts this DAO's entity to a Collection of instances of type {@link SessionDTO}.
     * @param entities
     * @return Collection<SessionDTO>     */
    List<SessionDTO> toSessionDTOCollection(Collection<Session> entities);

    /**
     * Converts an instance of type {@link SessionDTO} to this DAO's entity.
     * @param sessionDTO
     * @return Session
     */
    @InheritInverseConfiguration
    Session sessionDTOToEntity(SessionDTO sessionDTO);

    @BeanMapping(nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
    @InheritInverseConfiguration
    void updateSessionFromSessionDTO(SessionDTO sessionDTO, @MappingTarget Session entity);

}