// Generated by hibernate/SpringHibernateDaoImpl.vsl in andromda-spring-cartridge on $springUtils.date.
// license-header java merge-point
/**
 * This is only generated once! It will never be overwritten.
 * You can (and have to!) safely modify it by hand.
 */
package bw.co.roguesystems.comm.session;

import bw.co.roguesystems.comm.survey.SurveyRepository;
import bw.co.roguesystems.comm.survey.question.QuestionRepository;
import bw.co.roguesystems.comm.survey.response.SurveyResponseRepository;
import jakarta.persistence.EntityNotFoundException;

import org.springframework.stereotype.Repository;

/**
 * @see Session
 */
@Repository("sessionDao")
public class SessionDaoImpl
    extends SessionDaoBase
{
    
    public SessionDaoImpl(
        SurveyRepository surveyRepository,
        QuestionRepository questionRepository,
        SurveyResponseRepository surveyResponseRepository,
        SessionRepository sessionRepository
    ) {

        super(
            surveyRepository,
            questionRepository,
            surveyResponseRepository,
            sessionRepository
        );
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void toSessionDTO(
        Session source,
        SessionDTO target)
    {
        // TODO verify behavior of toSessionDTO
        super.toSessionDTO(source, target);
        // WARNING! No conversion for target.nextQuestion (can't convert source.getNextQuestion():bw.co.roguesystems.comm.survey.question.Question to bw.co.roguesystems.comm.survey.question.QuestionDTO
        // WARNING! No conversion for target.survey (can't convert source.getSurvey():bw.co.roguesystems.comm.survey.Survey to java.lang.String
        // WARNING! No conversion for target.questions (can't convert source.getQuestions():bw.co.roguesystems.comm.survey.question.Question to bw.co.roguesystems.comm.survey.question.QuestionDTO
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SessionDTO toSessionDTO(final Session entity)
    {
        // TODO verify behavior of toSessionDTO
        return super.toSessionDTO(entity);
    }

    /**
     * Retrieves the entity object that is associated with the specified value object
     * from the object store. If no such entity object exists in the object store,
     * a new, blank entity is created
     */
    private Session loadSessionFromSessionDTO(SessionDTO sessionDTO)
    {
        if (sessionDTO.getId() == null)
        {
            return  Session.Factory.newInstance();
        }
        else
        {
            return this.sessionRepository.findById(sessionDTO.getId())
                .orElseThrow(() -> new EntityNotFoundException("Entity not found for id: " + sessionDTO.getId()));
        }
    }

    /**
     * {@inheritDoc}
     */
    public Session sessionDTOToEntity(SessionDTO sessionDTO)
    {
        // TODO verify behavior of sessionDTOToEntity
        Session entity = this.loadSessionFromSessionDTO(sessionDTO);
        this.sessionDTOToEntity(sessionDTO, entity, true);
        return entity;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void sessionDTOToEntity(
        SessionDTO source,
        Session target,
        boolean copyIfNull)
    {
        // TODO verify behavior of sessionDTOToEntity
        super.sessionDTOToEntity(source, target, copyIfNull);
    }
}