// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by SpringWSImpl.java.vsl in andromda-webservices.
//
package bw.co.roguesystems.comm.survey.response;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;
import java.util.Collection;
import org.springframework.data.domain.Page;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.web.bind.annotation.RestController;

import bw.co.roguesystems.comm.AuditTracker;

@RestController
@Tag(name = "Surveys Setups", description = "Setups of surveys including the questions to be responded to.")
public class SurveyResponseApiImpl implements SurveyResponseApi {
        protected final SurveyResponseService surveyResponseService;
    
    public SurveyResponseApiImpl(
        SurveyResponseService surveyResponseService    ) {
        
        this.surveyResponseService = surveyResponseService;
    }



    @Override
    @Operation(summary = "Find Document Type", description = "Get the document type with the given id")
    public ResponseEntity<SurveyResponseDTO> findById(String id) throws Exception {
        try {
            return ResponseEntity.ok(surveyResponseService.findById(id));
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }


    @Override
    public ResponseEntity<Collection<SurveyResponseDTO>> getAll() throws Exception {
        try {
            return ResponseEntity.ok(surveyResponseService.getAll());
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }


    @Override
    public ResponseEntity<Page<SurveyResponseDTO>> getAllPaged(Integer pageNumber, Integer pageSize) throws Exception {
        try {
            return ResponseEntity.ok(surveyResponseService.getAll(pageNumber, pageSize));
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }


    @Override
    public ResponseEntity<Collection<SurveyResponseDTO>> getBySession(String sessionId) throws Exception {
        try {
            return ResponseEntity.ok(surveyResponseService.getBySession(sessionId));
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }


    @Override
    public ResponseEntity<Page<SurveyResponseDTO>> getBySessionPaged(String sessionId, Integer pageNumber, Integer pageSize) throws Exception {
        try {
            return ResponseEntity.ok(surveyResponseService.getBySession(sessionId, pageNumber, pageSize));
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }


    @Override
    public ResponseEntity<Collection<SurveyResponseDTO>> getBySessionReference(String sessionReference) throws Exception {
        try {
            return ResponseEntity.ok(surveyResponseService.getBySessionReference(sessionReference));
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }


    @Override
    public ResponseEntity<Page<SurveyResponseDTO>> getBySessionReferencePaged(String sessionReference, Integer pageNumber, Integer pageSize) throws Exception {
        try {
            return ResponseEntity.ok(surveyResponseService.getBySessionReference(sessionReference, pageNumber, pageSize));
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }


    @Override
    public ResponseEntity<Boolean> remove(String id) throws Exception {
        try {
            return ResponseEntity.ok(surveyResponseService.remove(id));
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }


    @Override
    public ResponseEntity<SurveyResponseDTO> save(SurveyResponseDTO response) throws Exception {
        try {
            Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
            AuditTracker.auditTrail(response, authentication);
            return ResponseEntity.ok(surveyResponseService.save(response));
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }


    @Override
    public ResponseEntity<Collection<SurveyResponseDTO>> search(String criteria) throws Exception {
        try {
            return ResponseEntity.ok(surveyResponseService.search(criteria));
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }
    
    /**
     * Gets the reference to <code>$serviceRef.daoName</code>.
     * @return surveyResponseService
     */
    protected SurveyResponseService getSurveyResponseService()
    {
        return this.surveyResponseService;
    }
}