// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by SpringWSImpl.java.vsl in andromda-webservices.
//
package bw.co.roguesystems.comm.session;

import bw.co.roguesystems.comm.AuditTracker;
import bw.co.roguesystems.comm.survey.response.SurveyResponseDTO;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;
import java.util.Collection;
import org.springframework.data.domain.Page;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.web.bind.annotation.RestController;

@RestController
@Tag(name = "Surveys Setups", description = "Setups of surveys including the questions to be responded to.")
public class SessionApiImpl implements SessionApi {
        protected final SessionService sessionService;
    
    public SessionApiImpl(
        SessionService sessionService    ) {
        
        this.sessionService = sessionService;
    }



    @Override
    @Operation(summary = "Find Document Type", description = "Get the document type with the given id")
    public ResponseEntity<SessionDTO> findById(String id) throws Exception {
        try {
            return ResponseEntity.ok(sessionService.findById(id));
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }


    @Override
    @Operation(summary = "Find Session By Reference", description = "Get session by the given reference")
    public ResponseEntity<SessionDTO> findByReference(String reference) throws Exception {
        try {
            return ResponseEntity.ok(sessionService.findByReference(reference));
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }


    @Override
    public ResponseEntity<Collection<SessionDTO>> getAll() throws Exception {
        try {
            return ResponseEntity.ok(sessionService.getAll());
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }


    @Override
    public ResponseEntity<Page<SessionDTO>> getAllPaged(Integer pageNumber, Integer pageSize) throws Exception {
        try {
            return ResponseEntity.ok(sessionService.getAll(pageNumber, pageSize));
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }


    @Override
    public ResponseEntity<Collection<SessionDTO>> getBySurvey(String surveyId) throws Exception {
        try {
            return ResponseEntity.ok(sessionService.getBySurvey(surveyId));
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }


    @Override
    public ResponseEntity<Page<SessionDTO>> getBySurveyPaged(String surveyId, Integer pageNumber, Integer pageSize) throws Exception {
        try {
            return ResponseEntity.ok(sessionService.getBySurvey(surveyId, pageNumber, pageSize));
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }


    @Override
    public ResponseEntity<Collection<SessionDTO>> getBySurveyReference(String surveyReference) throws Exception {
        try {
            return ResponseEntity.ok(sessionService.getBySurveyReference(surveyReference));
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }


    @Override
    public ResponseEntity<Page<SessionDTO>> getBySurveyReferencePaged(String surveyReference, Integer pageNumber, Integer pageSize) throws Exception {
        try {
            return ResponseEntity.ok(sessionService.getBySurveyReference(surveyReference, pageNumber, pageSize));
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }


    @Override
    public ResponseEntity<SessionDTO> next(String reference) throws Exception {
        try {
            return ResponseEntity.ok(sessionService.next(reference));
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }


    @Override
    public ResponseEntity<Boolean> remove(String id) throws Exception {
        try {
            return ResponseEntity.ok(sessionService.remove(id));
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }


    @Override
    public ResponseEntity<SessionDTO> save(SessionDTO session) throws Exception {
        try {
            Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
            AuditTracker.auditTrail(session, authentication);
            return ResponseEntity.ok(sessionService.save(session));
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }


    @Override
    public ResponseEntity<Collection<SessionDTO>> search(String criteria) throws Exception {
        try {
            return ResponseEntity.ok(sessionService.search(criteria));
        } catch (Exception e) {

            e.printStackTrace();
            throw e;
        } 
    }
    
    /**
     * Gets the reference to <code>$serviceRef.daoName</code>.
     * @return sessionService
     */
    protected SessionService getSessionService()
    {
        return this.sessionService;
    }
}