// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by SpringDao.vsl in andromda-spring-cartridge on $springUtils.date. Do not modify by hand!.
//
package bw.co.roguesystems.comm.message;

import java.util.Collection;
import java.util.List;
import org.mapstruct.BeanMapping;
import org.mapstruct.InheritInverseConfiguration;
import org.mapstruct.Mapper;
import org.mapstruct.MappingTarget;
import org.mapstruct.NullValuePropertyMappingStrategy;

@Mapper(
    componentModel = "spring"
)
public interface CommMessageMapper {
    
    /**
     * Converts this entity to an object of type {@link CommMessageDTO}.
     * @param entity
     * @return CommMessageDTO
     */
    CommMessageDTO toCommMessageDTO(CommMessage entity);

     /**
     * Converts this DAO's entity to a Collection of instances of type {@link CommMessageDTO}.
     * @param entities
     * @return Collection<CommMessageDTO>     */
    List<CommMessageDTO> toCommMessageDTOCollection(Collection<CommMessage> entities);

    /**
     * Converts an instance of type {@link CommMessageDTO} to this DAO's entity.
     * @param commMessageDTO
     * @return CommMessage
     */
    @InheritInverseConfiguration
    CommMessage commMessageDTOToEntity(CommMessageDTO commMessageDTO);

    @BeanMapping(nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
    @InheritInverseConfiguration
    void updateCommMessageFromCommMessageDTO(CommMessageDTO commMessageDTO, @MappingTarget CommMessage entity);

}