// Generated by hibernate/SpringHibernateDaoImpl.vsl in andromda-spring-cartridge on $springUtils.date.
// license-header java merge-point
/**
 * This is only generated once! It will never be overwritten.
 * You can (and have to!) safely modify it by hand.
 */
package bw.co.roguesystems.comm.message;

import org.springframework.stereotype.Repository;

import jakarta.persistence.EntityNotFoundException;

/**
 * @see CommMessage
 */
@Repository("commMessageDao")
public class CommMessageDaoImpl
    extends CommMessageDaoBase
{
    
    public CommMessageDaoImpl(
        CommMessageRepository commMessageRepository
    ) {

        super(
            commMessageRepository
        );
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void toCommMessageDTO(
        CommMessage source,
        CommMessageDTO target)
    {
        // TODO verify behavior of toCommMessageDTO
        super.toCommMessageDTO(source, target);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CommMessageDTO toCommMessageDTO(final CommMessage entity)
    {
        // TODO verify behavior of toCommMessageDTO
        return super.toCommMessageDTO(entity);
    }

    /**
     * Retrieves the entity object that is associated with the specified value object
     * from the object store. If no such entity object exists in the object store,
     * a new, blank entity is created
     */
    private CommMessage loadCommMessageFromCommMessageDTO(CommMessageDTO commMessageDTO)
    {
        if (commMessageDTO.getId() == null)
        {
            return  CommMessage.Factory.newInstance();
        }
        else
        {
            return this.commMessageRepository.findById(commMessageDTO.getId())
                .orElseThrow(() -> new EntityNotFoundException("Entity not found for id: " + commMessageDTO.getId()));
        }
    }

    /**
     * {@inheritDoc}
     */
    public CommMessage commMessageDTOToEntity(CommMessageDTO commMessageDTO)
    {
        // TODO verify behavior of commMessageDTOToEntity
        CommMessage entity = this.loadCommMessageFromCommMessageDTO(commMessageDTO);
        this.commMessageDTOToEntity(commMessageDTO, entity, true);
        return entity;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void commMessageDTOToEntity(
        CommMessageDTO source,
        CommMessage target,
        boolean copyIfNull)
    {
        // TODO verify behavior of commMessageDTOToEntity
        super.commMessageDTOToEntity(source, target, copyIfNull);
    }
}